/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AgentPanel: typeof import('./src/components/agent/AgentPanel.vue')['default']
    AnnotationDialog: typeof import('./src/components/dialog/AnnotationDialog.vue')['default']
    AnnotationList: typeof import('./src/components/novel/AnnotationList.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppIcon: typeof import('./src/components/common/AppIcon.vue')['default']
    AppLeftNav: typeof import('./src/components/layout/AppLeftNav.vue')['default']
    AppRight: typeof import('./src/components/layout/AppRight.vue')['default']
    CharacterList: typeof import('./src/components/novel/CharacterList.vue')['default']
    ContextMenu: typeof import('./src/components/common/ContextMenu.vue')['default']
    EditorToolbar: typeof import('./src/components/editor/EditorToolbar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExportDialog: typeof import('./src/components/dialog/ExportDialog.vue')['default']
    InlineEdit: typeof import('./src/components/common/InlineEdit.vue')['default']
    NewBookDialog: typeof import('./src/components/dialog/NewBookDialog.vue')['default']
    SearchDialog: typeof import('./src/components/dialog/SearchDialog.vue')['default']
    SettingsDialog: typeof import('./src/components/dialog/SettingsDialog.vue')['default']
    TiptapEditor: typeof import('./src/components/editor/TiptapEditor.vue')['default']
    WelcomeScreen: typeof import('./src/components/common/WelcomeScreen.vue')['default']
    WorldViewList: typeof import('./src/components/novel/WorldViewList.vue')['default']
  }
}
