/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./src/components/Content.vue')['default']
    Content_cancel: typeof import('./src/components/Content_cancel.vue')['default']
    ContentCtrl: typeof import('./src/components/module/ContentCtrl.vue')['default']
    ContentSet: typeof import('./src/components/module/ContentSet.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Header: typeof import('./src/components/Header.vue')['default']
    LeftNav: typeof import('./src/components/LeftNav.vue')['default']
    LeftNavCtrl: typeof import('./src/components/module/LeftNavCtrl.vue')['default']
    Right: typeof import('./src/components/Right.vue')['default']
    TitleChange: typeof import('./src/components/module/TitleChange.vue')['default']
  }
}
